# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/mara_/Desktop/ssc/incercare_proiect/incercare_proiect.cache/wt [current_project]
set_property parent.project_path C:/Users/mara_/Desktop/ssc/incercare_proiect/incercare_proiect.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/Users/mara_/Desktop/ssc/incercare_proiect/incercare_proiect.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet c:/Users/mara_/Desktop/ssc/incercare_proiect/incercare_proiect.srcs/sources_1/ip/fifo/fifo.dcp
set_property used_in_implementation false [get_files c:/Users/mara_/Desktop/ssc/incercare_proiect/incercare_proiect.srcs/sources_1/ip/fifo/fifo.dcp]
read_vhdl -library xil_defaultlib {
  C:/Users/mara_/Desktop/ssc/incercare_proiect/incercare_proiect.srcs/sources_1/new/sumatorNou.vhd
  C:/Users/mara_/Desktop/ssc/incercare_proiect/incercare_proiect.srcs/sources_1/new/scazator.vhd
  C:/Users/mara_/Desktop/ssc/incercare_proiect/incercare_proiect.srcs/sources_1/new/multiplication_axi4.vhd
  C:/Users/mara_/Desktop/ssc/incercare_proiect/incercare_proiect.srcs/sources_1/new/sumatorAxi4.vhd
  C:/Users/mara_/Desktop/ssc/incercare_proiect/incercare_proiect.srcs/sources_1/new/dividerAxi4.vhd
  C:/Users/mara_/Desktop/ssc/incercare_proiect/incercare_proiect.srcs/sources_1/new/InterpolareLagrange.vhd
  C:/Users/mara_/Desktop/ssc/incercare_proiect/incercare_proiect.srcs/sources_1/new/FiltruDeMedie.vhd
  C:/Users/mara_/Desktop/ssc/incercare_proiect/incercare_proiect.srcs/sources_1/new/FiltruPragAxi4.vhd
  C:/Users/mara_/Desktop/ssc/incercare_proiect/incercare_proiect.srcs/sources_1/new/tb_interpolare.vhd
  C:/Users/mara_/Desktop/ssc/incercare_proiect/incercare_proiect.srcs/sources_1/new/tb_medie.vhd
  C:/Users/mara_/Desktop/ssc/incercare_proiect/incercare_proiect.srcs/sources_1/new/tb_prag.vhd
  C:/Users/mara_/Desktop/ssc/incercare_proiect/incercare_proiect.srcs/sources_1/new/TestbenchSelector.vhd
  C:/Users/mara_/Desktop/ssc/incercare_proiect/incercare_proiect.srcs/sources_1/new/basys3.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc {{D:/Facultate/anul2/sem 2/MIPS16/test_env/test_env.srcs/constrs_1/new/basys3.xdc}}
set_property used_in_implementation false [get_files {{D:/Facultate/anul2/sem 2/MIPS16/test_env/test_env.srcs/constrs_1/new/basys3.xdc}}]


synth_design -top basys3 -part xc7a35tcpg236-1


write_checkpoint -force -noxdef basys3.dcp

catch { report_utilization -file basys3_utilization_synth.rpt -pb basys3_utilization_synth.pb }
